--1
CREATE TABLE USERS
(
    USER_ID    VARCHAR2(20),
    HOTEN      VARCHAR2(50)              NOT NULL,
    SDT        VARCHAR2(10)              NOT NULL,
    EMAIL      VARCHAR2(100),
    NGAYSINH   DATE,
    DIACHI     VARCHAR2(255),
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_SDT UNIQUE (SDT),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_SDT CHECK (REGEXP_LIKE(SDT, '^0[0-9]{9}$')),
    CONSTRAINT CK_USERS_EMAIL CHECK (EMAIL IS NULL OR
                                     REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CK_USERS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--2
CREATE TABLE ACCOUNT
(
    ACCOUNT_ID    VARCHAR2(20),
    USER_ID       VARCHAR2(20)              NOT NULL,
    USERNAME      VARCHAR2(50)              NOT NULL,
    PASSWORD_HASH VARCHAR2(255)             NOT NULL,
    STATUS        VARCHAR2(20)              NOT NULL,
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT UQ_ACCOUNT_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_ACCOUNT_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--3
CREATE TABLE ACCOUNT_TOKEN
(
    TOKEN_ID    VARCHAR2(20),
    ACCOUNT_ID  VARCHAR2(20)              NOT NULL,
    TOKEN_VALUE VARCHAR2(255)             NOT NULL,
    EXPIRED_AT  DATE                      NOT NULL,
    ISSUED_AT   DATE                      NOT NULL,
    IS_REVOKED  VARCHAR2(3)               NOT NULL,
    CREATED_AT  DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED  NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ACCOUNT_TOKEN PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_ACCOUNT_TOKEN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CONSTRAINT UQ_ACCOUNT_TOKEN_VALUE UNIQUE (TOKEN_VALUE),
    CONSTRAINT CK_ACCOUNT_TOKEN_REVOKED CHECK (IS_REVOKED IN ('YES', 'NO')),
    CONSTRAINT CK_ACCOUNT_TOKEN_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_ACCOUNT_TOKEN_DATES CHECK (EXPIRED_AT >= ISSUED_AT)
);
--4
CREATE TABLE FUNCTIONS
(
    FUNCTION_ID   VARCHAR2(20),
    NAME_FUNCTION VARCHAR2(100)             NOT NULL,
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_FUNCTIONS PRIMARY KEY (FUNCTION_ID),
    CONSTRAINT CK_FUNCTIONS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--5
CREATE TABLE ROLE
(
    ROLE_ID      VARCHAR2(20),
    FUNCTION_ID  VARCHAR2(20),
    ROLE_NAME    VARCHAR2(50)              NOT NULL,
    CAN_ADD      NUMBER(1) DEFAULT 0       NOT NULL,
    CAN_EDIT     NUMBER(1) DEFAULT 0       NOT NULL,
    CAN_DELETE   NUMBER(1) DEFAULT 0       NOT NULL,
    CAN_DOWNLOAD NUMBER(1) DEFAULT 0       NOT NULL,
    CAN_VIEW     NUMBER(1) DEFAULT 0       NOT NULL,
    CREATED_AT   DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED   NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT FK_ROLE_FUNCTION FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTIONS (FUNCTION_ID),
    CONSTRAINT CK_ROLE_CAN_ADD CHECK (CAN_ADD IN (0, 1)),
    CONSTRAINT CK_ROLE_CAN_EDIT CHECK (CAN_EDIT IN (0, 1)),
    CONSTRAINT CK_ROLE_CAN_DELETE CHECK (CAN_DELETE IN (0, 1)),
    CONSTRAINT CK_ROLE_CAN_DOWNLOAD CHECK (CAN_DOWNLOAD IN (0, 1)),
    CONSTRAINT CK_ROLE_CAN_VIEW CHECK (CAN_VIEW IN (0, 1)),
    CONSTRAINT CK_ROLE_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--6
CREATE TABLE ACCOUNT_ROLE
(
    ACCOUNT_ROLE_ID VARCHAR2(20),
    ACCOUNT_ID      VARCHAR2(20)              NOT NULL,
    ROLE_ID         VARCHAR2(20)              NOT NULL,
    CREATED_AT      DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED      NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ACCOUNT_ROLE PRIMARY KEY (ACCOUNT_ROLE_ID),
    CONSTRAINT FK_ACCOUNT_ROLE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
    CONSTRAINT CK_ACCOUNT_ROLE_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--7
CREATE TABLE ROLE_GROUP
(
    GROUP_ID    VARCHAR2(20),
    GROUP_NAME  VARCHAR2(100)             NOT NULL,
    DESCRIPTION VARCHAR2(255)             NOT NULL,
    CREATED_AT  DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED  NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ROLE_GROUP PRIMARY KEY (GROUP_ID),
    CONSTRAINT CK_ROLE_GROUP_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--8
CREATE TABLE ACCOUNT_ROLE_GROUP
(
    ACCOUNT_ROLE_GROUP_ID VARCHAR2(20),
    ACCOUNT_ID            VARCHAR2(20)              NOT NULL,
    GROUP_ID              VARCHAR2(20)              NOT NULL,
    CREATED_AT            DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED            NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ACCOUNT_ROLE_GROUP PRIMARY KEY (ACCOUNT_ROLE_GROUP_ID),
    CONSTRAINT FK_ARG_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ARG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ROLE_GROUP (GROUP_ID),
    CONSTRAINT CK_ACCOUNT_ROLE_GROUP_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--9
CREATE TABLE ACCOUNT_ROLE_GROUP_MAPPING
(
    MAPPING_ID VARCHAR2(20),
    ROLE_ID    VARCHAR2(20)              NOT NULL,
    GROUP_ID   VARCHAR2(20)              NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_ACCOUNT_ROLE_GROUP_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_ARGM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
    CONSTRAINT FK_ARGM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ROLE_GROUP (GROUP_ID),
    CONSTRAINT CK_ACCOUNT_ROLE_GROUP_MAPPING_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--10
CREATE TABLE HANG_KHACH_HANG
(
    MA_HANG    VARCHAR2(20),
    TEN_HANG   VARCHAR2(30)              NOT NULL UNIQUE,
    CHIET_KHAU DECIMAL   DEFAULT 0       NOT NULL,
    MUC_TIEN   NUMBER(12, 2)             NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_HANG_KHACH_HANG PRIMARY KEY (MA_HANG),
    CONSTRAINT CK_HANG_KH_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_HKKH_CHIET_KHAU_RANGE CHECK (CHIET_KHAU BETWEEN 0 AND 100),
    CONSTRAINT CK_HKKH_MUC_TIEN_NONNEG CHECK (MUC_TIEN >= 0)
);
--11
CREATE TABLE CHI_NHANH
(
    MACN          VARCHAR2(20),
    TEN_CHI_NHANH VARCHAR2(100)             NOT NULL,
    DIACHI        VARCHAR2(255)             NOT NULL,
    HOTLINE       VARCHAR2(10),
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_CHI_NHANH PRIMARY KEY (MACN),
    CONSTRAINT CK_CHI_NHANH_HOTLINE CHECK (HOTLINE IS NULL OR REGEXP_LIKE(HOTLINE, '^0[0-9]{9}$')),
    CONSTRAINT CK_CHI_NHANH_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--12
CREATE TABLE KHACH_HANG
(
    MAKH       VARCHAR2(20),
    USER_ID    VARCHAR2(20)                  NOT NULL,
    MA_HANG    VARCHAR2(20),
    TRANGTHAI  VARCHAR2(20)                  NOT NULL,
    DOANH_THU  NUMBER(12, 2) DEFAULT 0       NOT NULL,
    CREATED_AT DATE          DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1)     DEFAULT 0       NOT NULL,
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MAKH),
    CONSTRAINT FK_KHACH_HANG_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_KHACH_HANG_HANG FOREIGN KEY (MA_HANG) REFERENCES HANG_KHACH_HANG (MA_HANG),
    CONSTRAINT CK_KHACH_HANG_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_KHACHAHNG_TRANGTHAI CHECK (TRANGTHAI IN ('HOẠT ĐỘNG', 'ĐÃ XOÁ'))
);
--13
CREATE TABLE LOAI_NHAN_VIEN
(
    MALNV      VARCHAR2(20),
    VITRI      VARCHAR2(50)              NOT NULL,
    MUC_LUONG  NUMBER(12, 2)             NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_LOAI_NHAN_VIEN PRIMARY KEY (MALNV),
    CONSTRAINT CK_LOAI_NHAN_VIEN_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--14
CREATE TABLE NHAN_VIEN
(
    MANV       VARCHAR2(20),
    USER_ID    VARCHAR2(20)              NOT NULL,
    MALNV      VARCHAR2(20)              NOT NULL,
    MACN       VARCHAR2(20)              NOT NULL,
    NVL        DATE                      NOT NULL,
    CCCD       VARCHAR2(12),
    IS_QL      NUMBER(1)                 NOT NULL,
    TRANG_THAI VARCHAR2(20)              NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MANV),
    CONSTRAINT FK_NHAN_VIEN_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_NHAN_VIEN_LOAI FOREIGN KEY (MALNV) REFERENCES LOAI_NHAN_VIEN (MALNV),
    CONSTRAINT FK_NHAN_VIEN_CHI_NHANH FOREIGN KEY (MACN) REFERENCES CHI_NHANH (MACN),
    CONSTRAINT UQ_NHAN_VIEN_CCCD UNIQUE (CCCD),
    CONSTRAINT CK_NHAN_VIEN_CCCD CHECK (CCCD IS NULL OR REGEXP_LIKE(CCCD, '^[0-9]{12}$')),
    CONSTRAINT CK_NHAN_VIEN_IS_QL CHECK (IS_QL IN (0, 1)),
    CONSTRAINT CK_NHAN_VIEN_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--15
CREATE TABLE LOAI_THE_THAO
(
    MATT        VARCHAR2(20),
    TEN         VARCHAR2(50)              NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CREATED_AT  DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED  NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_LOAI_THE_THAO PRIMARY KEY (MATT),
    CONSTRAINT CK_LOAI_THE_THAO_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--16
CREATE TABLE KHU_VUC
(
    MAKV         VARCHAR2(20),
    MACN         VARCHAR2(20)              NOT NULL,
    MATT         VARCHAR2(20)              NOT NULL,
    SO_LUONG_SAN NUMBER(5)                 NOT NULL,
    CREATED_AT   DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED   NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_KHU_VUC PRIMARY KEY (MAKV),
    CONSTRAINT FK_KHU_VUC_CHI_NHANH FOREIGN KEY (MACN) REFERENCES CHI_NHANH (MACN),
    CONSTRAINT FK_KHU_VUC_LOAI_THE_THAO FOREIGN KEY (MATT) REFERENCES LOAI_THE_THAO (MATT),
    CONSTRAINT CK_KHU_VUC_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_KHU_VUC_SO_LUONG_SAN CHECK (SO_LUONG_SAN >= 0)
);
--17
CREATE TABLE SAN_CON
(
    MASAN      VARCHAR2(20),
    MAKV       VARCHAR2(20)              NOT NULL,
    TRANGTHAI  VARCHAR2(30)              NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_SAN_CON PRIMARY KEY (MASAN),
    CONSTRAINT FK_SAN_CON_KHU_VUC FOREIGN KEY (MAKV) REFERENCES KHU_VUC (MAKV),
    CONSTRAINT CK_SAN_CON_TRANGTHAI CHECK (TRANGTHAI IN ('ĐANG HOẠT ĐỘNG', 'BẢO TRÌ')),
    CONSTRAINT CK_SAN_CON_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

--18
CREATE TABLE BANG_GIA
(
    MABG       VARCHAR2(20),
    MAKV       VARCHAR2(20)              NOT NULL,
    GIOBATDAU  NUMBER(2)                 NOT NULL,
    GIOKETTHUC NUMBER(2)                 NOT NULL,
    GIA        NUMBER(12, 2)             NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_BG PRIMARY KEY (MABG),
    CONSTRAINT FK_BG_KHU_VUC FOREIGN KEY (MAKV) REFERENCES KHU_VUC (MAKV),
    CONSTRAINT CK_BG_GIO_BAT_DAU CHECK (GIOBATDAU BETWEEN 0 AND 23),
    CONSTRAINT CK_BG_GIO_KET_THUC CHECK (GIOKETTHUC BETWEEN 1 AND 24),
    CONSTRAINT CK_BG_THOI_LUONG_1_GIO CHECK (GIOKETTHUC = GIOBATDAU + 1),
    CONSTRAINT CK_BG_GIA_DUONG CHECK (GIA > 0),
    CONSTRAINT CK_BG_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);


CREATE UNIQUE INDEX UQ_BG_ACTIVE_MAKV_GIO
    ON BANG_GIA (
        CASE WHEN IS_DELETED = 0 THEN MAKV END,
        CASE WHEN IS_DELETED = 0 THEN GIOBATDAU END,
        CASE WHEN IS_DELETED = 0 THEN GIOKETTHUC END
    );
--19
CREATE TABLE HOA_DON
(
    MAHD       VARCHAR2(20),
    MAKH       VARCHAR2(20)                  NOT NULL,
    MANV       VARCHAR2(20)                  NOT NULL,
    TIEN_COC   NUMBER(12, 2) DEFAULT 0       NOT NULL,
    GIAMGIA    DECIMAL       DEFAULT 0       NOT NULL,
    TONGGIATRI NUMBER(12, 2) DEFAULT 0       NOT NULL,
    TRANGTHAI  VARCHAR2(30)                  NOT NULL,
    TONGTIEN   NUMBER(12, 2) DEFAULT 0       NOT NULL,
    CREATED_AT DATE          DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1)     DEFAULT 0       NOT NULL,
    CONSTRAINT PK_HOA_DON PRIMARY KEY (MAHD),
    CONSTRAINT FK_HOA_DON_KHACH_HANG FOREIGN KEY (MAKH) REFERENCES KHACH_HANG (MAKH),
    CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (MANV) REFERENCES NHAN_VIEN (MANV),
    CONSTRAINT CK_HOA_DON_TRANG_THAI CHECK (TRANGTHAI IN (
                                                          'CHƯA THANH TOÁN', 'ĐÃ THANH TOÁN', 'ĐÃ HUỶ'
        )),
    CONSTRAINT CK_HOA_DON_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_HOA_DON_GIAMGIA_RANGE CHECK (GIAMGIA BETWEEN 0 AND 100),
    CONSTRAINT CK_HOA_DON_TIEN_COC_NONNEG CHECK (TIEN_COC >= 0),
    CONSTRAINT CK_HOA_DON_TONGGIATRI_NONNEG CHECK (TONGGIATRI >= 0),
    CONSTRAINT CK_HOA_DON_TONGTIEN_NONNEG CHECK (TONGTIEN >= 0)
);
--20
CREATE TABLE CHI_TIET_HOA_DON_THUE_SAN
(
    MACT_THUE_SAN VARCHAR2(20),
    MAHD          VARCHAR2(20)                  NOT NULL,
    MASAN         VARCHAR2(20)                  NOT NULL,
    MABG          VARCHAR2(20)                  NOT NULL,
    NGAYTHUE      DATE                          NOT NULL,
    DON_GIA_THUE  NUMBER(12, 2) DEFAULT 0       NOT NULL,
    TRANGTHAI     VARCHAR2(30)                  NOT NULL,
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1)     DEFAULT 0       NOT NULL,
    CONSTRAINT PK_CTHD_THUE_SAN PRIMARY KEY (MACT_THUE_SAN),
    CONSTRAINT FK_CTHD_THUE_SAN_HOA_DON FOREIGN KEY (MAHD) REFERENCES HOA_DON (MAHD),
    CONSTRAINT FK_CTHD_THUE_SAN_SAN_CON FOREIGN KEY (MASAN) REFERENCES SAN_CON (MASAN),
    CONSTRAINT FK_CTHD_THUE_SAN_BANG_GIA FOREIGN KEY (MABG) REFERENCES BANG_GIA (MABG),
    CONSTRAINT CK_CTHD_THUE_SAN_TRANGTHAI CHECK (TRANGTHAI IN ('ĐÃ ĐẶT CHỜ CỌC', 'ĐÃ CỌC', 'ĐÃ XÁC NHẬN', 'ĐÃ HUỶ',
                                                               'ĐANG SỬ DỤNG', 'ĐÃ HOÀN THÀNH')),
    CONSTRAINT CK_CTHD_THUE_SAN_DON_GIA CHECK (DON_GIA_THUE >= 0),
    CONSTRAINT CK_CTHD_THUE_SAN_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX UQ_CTHD_TS_LICH_ACTIVE
    ON CHI_TIET_HOA_DON_THUE_SAN (
        CASE WHEN IS_DELETED = 0 AND TRANGTHAI <> 'ĐÃ HUỶ' THEN MASAN END,
        CASE WHEN IS_DELETED = 0 AND TRANGTHAI <> 'ĐÃ HUỶ' THEN TRUNC(NGAYTHUE) END,
        CASE WHEN IS_DELETED = 0 AND TRANGTHAI <> 'ĐÃ HUỶ' THEN MABG END
    );
--21
CREATE TABLE SAN_PHAM
(
    MASP       VARCHAR2(20),
    TENSP      VARCHAR2(100)             NOT NULL,
    DVT        VARCHAR2(20)              NOT NULL,
    GIA        NUMBER(12, 2)             NOT NULL,
    SL_TON     NUMBER(10)                NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_SAN_PHAM PRIMARY KEY (MASP),
    CONSTRAINT CK_SAN_PHAM_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_SAN_PHAM_SL_TON CHECK (SL_TON >= 0),
    CONSTRAINT CK_SAN_PHAM_GIA_DUONG CHECK (GIA > 0)
);
--22
CREATE TABLE DUNG_CU_THE_THAO
(
    MADC       VARCHAR2(20),
    TENDC      VARCHAR2(100)             NOT NULL,
    DVT        VARCHAR2(20)              NOT NULL,
    GIA        NUMBER(12, 2)             NOT NULL,
    SL_TON     NUMBER(10)                NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_DUNG_CU_THE_THAO PRIMARY KEY (MADC),
    CONSTRAINT CK_DUNG_CU_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_DUNG_CU_SL_TON CHECK (SL_TON >= 0),
    CONSTRAINT CK_DUNG_CU_GIA_DUONG CHECK (GIA > 0)
);

--23
CREATE TABLE CHI_TIET_HOA_DON_DICH_VU_DA_DUNG
(
    MACT_DICH_VU VARCHAR2(20),
    MAHD         VARCHAR2(20)              NOT NULL,
    MASP         VARCHAR2(20),
    MADC         VARCHAR2(20),
    SL           NUMBER(10)                NOT NULL,
    DON_GIA      NUMBER(12, 2) DEFAULT 0   NOT NULL,
    TRANGTHAI    VARCHAR2(30)              NOT NULL,
    CREATED_AT   DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED   NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_CTHD_DICH_VU PRIMARY KEY (MACT_DICH_VU),
    CONSTRAINT FK_CTHD_DICH_VU_HOA_DON FOREIGN KEY (MAHD) REFERENCES HOA_DON (MAHD),
    CONSTRAINT FK_CTHD_DICH_VU_SAN_PHAM FOREIGN KEY (MASP) REFERENCES SAN_PHAM (MASP),
    CONSTRAINT FK_CTHD_DICH_VU_DUNG_CU FOREIGN KEY (MADC) REFERENCES DUNG_CU_THE_THAO (MADC),
    CONSTRAINT CK_CTHD_DICH_VU_LOAI CHECK (
        (MASP IS NOT NULL AND MADC IS NULL)
            OR
        (MASP IS NULL AND MADC IS NOT NULL)
        ),
    CONSTRAINT CK_CTHD_DICH_VU_TRANGTHAI CHECK (TRANGTHAI IN ('ĐANG SỬ DỤNG', 'ĐÃ HOÀN THÀNH')),
    CONSTRAINT CK_CTHD_DICH_VU_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_CTHD_DV_SL_DUONG CHECK (SL > 0),
    CONSTRAINT CK_CTHD_DV_DON_GIA CHECK (DON_GIA >= 0)
);
--24
CREATE TABLE NHA_CUNG_CAP
(
    MANCC      VARCHAR2(20),
    TENNCC     VARCHAR2(100)             NOT NULL,
    SDT        VARCHAR2(10)              NOT NULL,
    EMAIL      VARCHAR2(100),
    WEBSITE    VARCHAR2(100),
    DIACHI     VARCHAR2(255)             NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MANCC),
    CONSTRAINT CK_NCC_SDT CHECK (REGEXP_LIKE(SDT, '^0[0-9]{9}$')),
    CONSTRAINT CK_NCC_EMAIL CHECK (EMAIL IS NULL OR
                                   REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CK_NHA_CUNG_CAP_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
--25
CREATE TABLE NHAP_HANG
(
    MANH       VARCHAR2(20),
    MANCC      VARCHAR2(20)              NOT NULL,
    MANV       VARCHAR2(20)              NOT NULL,
    MACHUNGTU  VARCHAR2(20)              NOT NULL,
    TRI_GIA    NUMBER(12, 2)             NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_NHAP_HANG PRIMARY KEY (MANH),
    CONSTRAINT FK_NHAP_HANG_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP (MANCC),
    CONSTRAINT FK_NHAP_HANG_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN (MANV),
    CONSTRAINT CK_NHAP_HANG_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_NHAP_HANG_TRI_GIA CHECK (TRI_GIA > 0)
);
--26
CREATE TABLE CHI_TIET_NHAP_HANG
(
    MACTNH_SP     VARCHAR2(20),
    MANH          VARCHAR2(20)              NOT NULL,
    MASP          VARCHAR2(20)              NOT NULL,
    SLTHEOCHUNGTU NUMBER(10)                NOT NULL,
    SLTHUCNHAP    NUMBER(10)                NOT NULL,
    DONGIA        NUMBER(12)                NOT NULL,
    VAT           DECIMAL                   NOT NULL,
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_CHI_TIET_NHAP_HANG PRIMARY KEY (MACTNH_SP),
    CONSTRAINT FK_CTNH_NHAP_HANG FOREIGN KEY (MANH) REFERENCES NHAP_HANG (MANH),
    CONSTRAINT FK_CTNH_SAN_PHAM FOREIGN KEY (MASP) REFERENCES SAN_PHAM (MASP),
    CONSTRAINT CK_CTNH_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_CTNHSP_SLTHUCNHAP_DUONG CHECK (SLTHUCNHAP > 0),
    CONSTRAINT CK_CTNSP_SLTHEOCHUNGTU_DUONG CHECK (SLTHEOCHUNGTU > 0),
    CONSTRAINT CK_CTNSP_DONGIA_DUONG CHECK (DONGIA > 0),
    CONSTRAINT CK_CTNSP_VAT_RANGE CHECK (VAT BETWEEN 0 AND 100)
);
--27
CREATE TABLE CHI_TIET_NHAP_DUNG_CU
(
    MACTNH_DC     VARCHAR2(20),
    MANH          VARCHAR2(20)              NOT NULL,
    MADC          VARCHAR2(20)              NOT NULL,
    SLTHEOCHUNGTU NUMBER(10)                NOT NULL,
    SLTHUCNHAP    NUMBER(10)                NOT NULL,
    CKTM          NUMBER(5) DEFAULT 0       NOT NULL,
    DONGIA        NUMBER(12)                NOT NULL,
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_CHI_TIET_NHAP_DUNG_CU PRIMARY KEY (MACTNH_DC),
    CONSTRAINT FK_CTNDC_NHAP_HANG FOREIGN KEY (MANH) REFERENCES NHAP_HANG (MANH),
    CONSTRAINT FK_CTNDC_DUNG_CU FOREIGN KEY (MADC) REFERENCES DUNG_CU_THE_THAO (MADC),
    CONSTRAINT CK_CTNDC_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_CTNDC_SLTHUCNHAP_DUONG CHECK (SLTHUCNHAP > 0),
    CONSTRAINT CK_CTNDC_SLTHEOCHUNGTU_DUONG CHECK (SLTHEOCHUNGTU > 0),
    CONSTRAINT CK_CTNDC_CKTM_RANGE CHECK (CKTM BETWEEN 0 AND 100),
    CONSTRAINT CK_CTNDC_DONGIA_DUONG CHECK (DONGIA > 0)
);
--28
CREATE TABLE EMAIL_OTP
(
    OTP_ID        VARCHAR2(20),
    EMAIL         VARCHAR2(100)             NOT NULL,
    OTP_CODE      VARCHAR2(6)               NOT NULL,
    PURPOSE       VARCHAR2(20)              NOT NULL,
    EXPIRED_AT    DATE                      NOT NULL,
    USED_AT       DATE,
    ATTEMPT_COUNT NUMBER(3) DEFAULT 0       NOT NULL,
    CREATED_AT    DATE      DEFAULT SYSDATE NOT NULL,
    IS_DELETED    NUMBER(1) DEFAULT 0       NOT NULL,
    CONSTRAINT PK_EMAIL_OTP PRIMARY KEY (OTP_ID),
    CONSTRAINT CK_EMAIL_OTP_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CK_EMAIL_OTP_CODE CHECK (REGEXP_LIKE(OTP_CODE, '^[0-9]{6}$')),
    CONSTRAINT CK_EMAIL_OTP_PURPOSE CHECK (PURPOSE IN ('REGISTER', 'RESET_PASSWORD')),
    CONSTRAINT CK_EMAIL_OTP_ATTEMPT CHECK (ATTEMPT_COUNT >= 0),
    CONSTRAINT CK_EMAIL_OTP_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);
