-- =========================================================
-- TEST DATA CHO MODULE COURT
-- Muc tieu:
-- - Du data cho CourtTest (CN_TEST_01, CN_TEST_02, CN_TEST_03)
-- - Test tim kiem/them/sua/xoa san con
-- - Co 1 ban ghi SAN_CON da xoa mem de test bo loc IS_DELETED
-- =========================================================

-- 1) LOAI THE THAO
MERGE INTO LOAI_THE_THAO t
USING (SELECT 'MATT_TEST_BD' AS MATT, 'BONG DA' AS TEN FROM dual) s
ON (t.MATT = s.MATT)
WHEN MATCHED THEN
    UPDATE SET t.TEN = s.TEN, t.DESCRIPTION = 'Loai the thao test', t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MATT, TEN, DESCRIPTION, IS_DELETED)
    VALUES (s.MATT, s.TEN, 'Loai the thao test', 0);

MERGE INTO LOAI_THE_THAO t
USING (SELECT 'MATT_TEST_CL' AS MATT, 'CAU LONG' AS TEN FROM dual) s
ON (t.MATT = s.MATT)
WHEN MATCHED THEN
    UPDATE SET t.TEN = s.TEN, t.DESCRIPTION = 'Loai the thao test', t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MATT, TEN, DESCRIPTION, IS_DELETED)
    VALUES (s.MATT, s.TEN, 'Loai the thao test', 0);

MERGE INTO LOAI_THE_THAO t
USING (SELECT 'MATT_TEST_TN' AS MATT, 'TENNIS' AS TEN FROM dual) s
ON (t.MATT = s.MATT)
WHEN MATCHED THEN
    UPDATE SET t.TEN = s.TEN, t.DESCRIPTION = 'Loai the thao test', t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MATT, TEN, DESCRIPTION, IS_DELETED)
    VALUES (s.MATT, s.TEN, 'Loai the thao test', 0);

-- 2) CHI NHANH TEST
MERGE INTO CHI_NHANH t
USING (
    SELECT 'CN_TEST_01' AS MACN, 'Chi nhanh test 01' AS TEN_CHI_NHANH, 'Thu Duc' AS DIACHI, '0911111111' AS HOTLINE FROM dual
) s
ON (t.MACN = s.MACN)
WHEN MATCHED THEN
    UPDATE SET t.TEN_CHI_NHANH = s.TEN_CHI_NHANH, t.DIACHI = s.DIACHI, t.HOTLINE = s.HOTLINE, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MACN, TEN_CHI_NHANH, DIACHI, HOTLINE, IS_DELETED)
    VALUES (s.MACN, s.TEN_CHI_NHANH, s.DIACHI, s.HOTLINE, 0);

MERGE INTO CHI_NHANH t
USING (
    SELECT 'CN_TEST_02' AS MACN, 'Chi nhanh test 02' AS TEN_CHI_NHANH, 'Quan 7' AS DIACHI, '0922222222' AS HOTLINE FROM dual
) s
ON (t.MACN = s.MACN)
WHEN MATCHED THEN
    UPDATE SET t.TEN_CHI_NHANH = s.TEN_CHI_NHANH, t.DIACHI = s.DIACHI, t.HOTLINE = s.HOTLINE, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MACN, TEN_CHI_NHANH, DIACHI, HOTLINE, IS_DELETED)
    VALUES (s.MACN, s.TEN_CHI_NHANH, s.DIACHI, s.HOTLINE, 0);

MERGE INTO CHI_NHANH t
USING (
    SELECT 'CN_TEST_03' AS MACN, 'Chi nhanh test 03' AS TEN_CHI_NHANH, 'Binh Thanh' AS DIACHI, '0933333333' AS HOTLINE FROM dual
) s
ON (t.MACN = s.MACN)
WHEN MATCHED THEN
    UPDATE SET t.TEN_CHI_NHANH = s.TEN_CHI_NHANH, t.DIACHI = s.DIACHI, t.HOTLINE = s.HOTLINE, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MACN, TEN_CHI_NHANH, DIACHI, HOTLINE, IS_DELETED)
    VALUES (s.MACN, s.TEN_CHI_NHANH, s.DIACHI, s.HOTLINE, 0);

-- 3) KHU VUC THEO CHI NHANH
MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_01A' AS MAKV, 'CN_TEST_01' AS MACN, 'MATT_TEST_BD' AS MATT, 3 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_01B' AS MAKV, 'CN_TEST_01' AS MACN, 'MATT_TEST_CL' AS MATT, 4 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_02A' AS MAKV, 'CN_TEST_02' AS MACN, 'MATT_TEST_TN' AS MATT, 2 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_02B' AS MAKV, 'CN_TEST_02' AS MACN, 'MATT_TEST_CL' AS MATT, 3 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_03A' AS MAKV, 'CN_TEST_03' AS MACN, 'MATT_TEST_BD' AS MATT, 5 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

MERGE INTO KHU_VUC t
USING (SELECT 'KV_TEST_03B' AS MAKV, 'CN_TEST_03' AS MACN, 'MATT_TEST_TN' AS MATT, 2 AS SO_LUONG_SAN FROM dual) s
ON (t.MAKV = s.MAKV)
WHEN MATCHED THEN
    UPDATE SET t.MACN = s.MACN, t.MATT = s.MATT, t.SO_LUONG_SAN = s.SO_LUONG_SAN, t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (MAKV, MACN, MATT, SO_LUONG_SAN, IS_DELETED)
    VALUES (s.MAKV, s.MACN, s.MATT, s.SO_LUONG_SAN, 0);

-- 4) SAN CON TEST (co ca dang hoat dong va bao tri)
MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0101' AS MASAN, 'KV_TEST_01A' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0102' AS MASAN, 'KV_TEST_01A' AS MAKV, 'BẢO TRÌ' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0103' AS MASAN, 'KV_TEST_01B' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0201' AS MASAN, 'KV_TEST_02A' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0202' AS MASAN, 'KV_TEST_02B' AS MAKV, 'BẢO TRÌ' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0301' AS MASAN, 'KV_TEST_03A' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_0302' AS MASAN, 'KV_TEST_03B' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 0 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

-- Ban ghi xoa mem de test bo loc tren man list
MERGE INTO SAN_CON t
USING (SELECT 'SAN_TEST_DELETED_01' AS MASAN, 'KV_TEST_01A' AS MAKV, 'ĐANG HOẠT ĐỘNG' AS TRANGTHAI, 1 AS IS_DELETED FROM dual) s
ON (t.MASAN = s.MASAN)
WHEN MATCHED THEN
    UPDATE SET t.MAKV = s.MAKV, t.TRANGTHAI = s.TRANGTHAI, t.IS_DELETED = s.IS_DELETED
WHEN NOT MATCHED THEN
    INSERT (MASAN, MAKV, TRANGTHAI, IS_DELETED) VALUES (s.MASAN, s.MAKV, s.TRANGTHAI, s.IS_DELETED);

COMMIT;

-- 5) VERIFY NHANH SAU KHI INSERT
-- Danh sach san theo 3 chi nhanh test:
SELECT kv.MACN, sc.MASAN, sc.MAKV, sc.TRANGTHAI, sc.IS_DELETED
FROM SAN_CON sc
JOIN KHU_VUC kv ON kv.MAKV = sc.MAKV
WHERE kv.MACN IN ('CN_TEST_01', 'CN_TEST_02', 'CN_TEST_03')
ORDER BY kv.MACN, sc.MASAN;
