--RB53
CREATE OR REPLACE PROCEDURE PRC_TINH_TONG_GIA_TRI_HOA_DON(
    P_MAHD IN HOA_DON.MAHD%TYPE
)
AS
    V_TONGTIENTHUESAN NUMBER(12, 2) := 0;
    V_TONGTIENDICHVU  NUMBER(12, 2) := 0;
BEGIN
    SELECT NVL(SUM(BG.GIA), 0)
    INTO V_TONGTIENTHUESAN
    FROM CHI_TIET_HOA_DON_THUE_SAN CT
             JOIN SAN_CON SC
                  ON SC.MASAN = CT.MASAN
                      AND SC.IS_DELETED = 0
             JOIN BANG_GIA BG
                  ON BG.MAKV = SC.MAKV
                      AND BG.MAKG = CT.MAKG
                      AND BG.IS_DELETED = 0
    WHERE CT.MAHD = P_MAHD
      AND CT.IS_DELETED = 0
      AND CT.TRANGTHAI <> 'ĐÃ HUỶ';

    SELECT NVL(SUM(
                       CASE
                           WHEN CT.MASP IS NOT NULL THEN CT.SL * SP.GIA
                           WHEN CT.MADC IS NOT NULL THEN CT.SL * DC.GIA
                           ELSE 0
                           END
               ), 0)
    INTO V_TONGTIENDICHVU
    FROM CHI_TIET_HOA_DON_DICH_VU_DA_DUNG CT
             LEFT JOIN SAN_PHAM SP
                       ON SP.MASP = CT.MASP
                           AND SP.IS_DELETED = 0
             LEFT JOIN DUNG_CU_THE_THAO DC
                       ON DC.MADC = CT.MADC
                           AND DC.IS_DELETED = 0
    WHERE CT.MAHD = P_MAHD
      AND CT.IS_DELETED = 0;

    UPDATE HOA_DON
    SET TONGGIATRI = V_TONGTIENTHUESAN + V_TONGTIENDICHVU
    WHERE MAHD = P_MAHD;
END;
/

CREATE OR REPLACE TRIGGER TRG_FIUD_CTHD_THUE_SAN_RECALC_TONG_GIA_TRI_HOA_DON
    FOR INSERT OR UPDATE OR DELETE
    ON CHI_TIET_HOA_DON_THUE_SAN
    COMPOUND TRIGGER

    TYPE T_MAHD_LIST IS TABLE OF HOA_DON.MAHD%TYPE INDEX BY PLS_INTEGER;
    G_MAHD_LIST T_MAHD_LIST;
    G_COUNT PLS_INTEGER := 0;

    PROCEDURE ADD_MAHD(P_MAHD IN HOA_DON.MAHD%TYPE) IS
    BEGIN
        IF P_MAHD IS NOT NULL THEN
            G_COUNT := G_COUNT + 1;
            G_MAHD_LIST(G_COUNT) := P_MAHD;
        END IF;
    END;

BEFORE EACH ROW IS
BEGIN
    IF INSERTING THEN
        ADD_MAHD(:NEW.MAHD);

    ELSIF DELETING THEN
        ADD_MAHD(:OLD.MAHD);

    ELSIF UPDATING THEN
        IF NVL(:OLD.MAHD, '#') <> NVL(:NEW.MAHD, '#')
           OR NVL(:OLD.MASAN, '#') <> NVL(:NEW.MASAN, '#')
           OR NVL(:OLD.MAKG, '#') <> NVL(:NEW.MAKG, '#')
           OR NVL(:OLD.IS_DELETED, -1) <> NVL(:NEW.IS_DELETED, -1)
           OR (:OLD.TRANGTHAI = 'ĐÃ HUỶ' AND :NEW.TRANGTHAI <> 'ĐÃ HUỶ')
           OR (:OLD.TRANGTHAI <> 'ĐÃ HUỶ' AND :NEW.TRANGTHAI = 'ĐÃ HUỶ')
        THEN
            ADD_MAHD(:NEW.MAHD);

            IF NVL(:OLD.MAHD, '#') <> NVL(:NEW.MAHD, '#') THEN
                ADD_MAHD(:OLD.MAHD);
            END IF;
        END IF;
    END IF;
END BEFORE EACH ROW;

AFTER STATEMENT IS
BEGIN
    FOR I IN 1 .. G_COUNT LOOP
        PRC_TINH_TONG_GIA_TRI_HOA_DON(G_MAHD_LIST(I));
    END LOOP;
END AFTER STATEMENT;

END;
/

CREATE OR REPLACE TRIGGER TRG_FIUD_CTHD_DICH_VU_RECALC_TONG_GIA_TRI_HOA_DON
    FOR INSERT OR UPDATE OR DELETE
    ON CHI_TIET_HOA_DON_DICH_VU_DA_DUNG
    COMPOUND TRIGGER

    TYPE T_MAHD_LIST IS TABLE OF HOA_DON.MAHD%TYPE INDEX BY PLS_INTEGER;
    G_MAHD_LIST T_MAHD_LIST;
    G_COUNT PLS_INTEGER := 0;

    PROCEDURE ADD_MAHD(P_MAHD IN HOA_DON.MAHD%TYPE) IS
    BEGIN
        IF P_MAHD IS NOT NULL THEN
            G_COUNT := G_COUNT + 1;
            G_MAHD_LIST(G_COUNT) := P_MAHD;
        END IF;
    END;

BEFORE EACH ROW IS
BEGIN
    IF INSERTING THEN
        ADD_MAHD(:NEW.MAHD);

    ELSIF DELETING THEN
        ADD_MAHD(:OLD.MAHD);

    ELSIF UPDATING THEN
        IF NVL(:OLD.MAHD, '#') <> NVL(:NEW.MAHD, '#')
           OR NVL(:OLD.MASP, '#') <> NVL(:NEW.MASP, '#')
           OR NVL(:OLD.MADC, '#') <> NVL(:NEW.MADC, '#')
           OR NVL(:OLD.SL, -1) <> NVL(:NEW.SL, -1)
           OR NVL(:OLD.IS_DELETED, -1) <> NVL(:NEW.IS_DELETED, -1)
        THEN
            ADD_MAHD(:NEW.MAHD);

            IF NVL(:OLD.MAHD, '#') <> NVL(:NEW.MAHD, '#') THEN
                ADD_MAHD(:OLD.MAHD);
            END IF;
        END IF;
    END IF;
END BEFORE EACH ROW;

AFTER STATEMENT IS
BEGIN
    FOR I IN 1 .. G_COUNT LOOP
        PRC_TINH_TONG_GIA_TRI_HOA_DON(G_MAHD_LIST(I));
    END LOOP;
END AFTER STATEMENT;

END;
/
--RB57,58
CREATE OR REPLACE TRIGGER TRG_BIU_ELEMENTS_HOA_DON
    BEFORE INSERT OR UPDATE OF MAKH, GIAMGIA, TIEN_COC, TONGGIATRI
    ON HOA_DON
    FOR EACH ROW
DECLARE
    V_MA_HANG       KHACH_HANG.MA_HANG%TYPE;
    V_CHIET_KHAU    HANG_KHACH_HANG.CHIET_KHAU%TYPE;
    V_TIEN_THUE_SAN NUMBER(12, 2) := 0;
BEGIN
    SELECT MA_HANG
    INTO V_MA_HANG
    FROM KHACH_HANG
    WHERE MAKH = :NEW.MAKH
      AND IS_DELETED = 0;

    IF V_MA_HANG IS NOT NULL THEN
        SELECT CHIET_KHAU
        INTO V_CHIET_KHAU
        FROM HANG_KHACH_HANG
        WHERE MA_HANG = V_MA_HANG
          AND IS_DELETED = 0;
        :NEW.GIAMGIA := V_CHIET_KHAU;
    end if;

    IF NVL(:NEW.GIAMGIA, 0) < 0 OR NVL(:NEW.GIAMGIA, 0) > 100 THEN
        RAISE_APPLICATION_ERROR(
                -20057,
                'GIAMGIA phải nằm trong khoảng từ 0 đến 100.'
        );
    end IF;

    SELECT NVL(SUM(BG.GIA), 0)
    INTO V_TIEN_THUE_SAN
    FROM CHI_TIET_HOA_DON_THUE_SAN CT
             JOIN SAN_CON SC
                  ON SC.MASAN = CT.MASAN
                      AND SC.IS_DELETED = 0
             JOIN BANG_GIA BG
                  ON BG.MAKV = SC.MAKV
                      AND BG.MAKG = CT.MAKG
                      AND BG.IS_DELETED = 0
    WHERE CT.MAHD = :NEW.MAHD
      AND CT.IS_DELETED = 0
      AND CT.TRANGTHAI <> 'ĐÃ HUỶ';

    IF NVL(:NEW.TIEN_COC, 0) > 0 THEN
        IF ABS(:NEW.TIEN_COC - ROUND(V_TIEN_THUE_SAN * 0.7, 2)) > 0.01 THEN
            RAISE_APPLICATION_ERROR(
                    -20058,
                    'TIEN_COC phải bằng 70% tiền thuê sân.'
            );
        END IF;
    ELSE
        :NEW.TIEN_COC := 0;
    END IF;

    :NEW.TONGTIEN := ROUND(
            :NEW.TONGGIATRI * (1 - NVL(:NEW.GIAMGIA, 0) / 100)
                - NVL(:NEW.TIEN_COC, 0),
            2
                     );

    IF :NEW.TONGTIEN < 0 THEN
        RAISE_APPLICATION_ERROR(
                -20059,
                'TONGTIEN không được âm.'
        );
    END IF;
end;
/

--RB61
CREATE OR REPLACE TRIGGER TRG_CHECK_STATUS_HOA_DON
    BEFORE UPDATE OF TRANGTHAI
    ON HOA_DON
    FOR EACH ROW
DECLARE
    V_COUNT PLS_INTEGER := 0;
BEGIN
    IF :NEW.TRANGTHAI = 'ĐÃ THANH TOÁN' THEN
        IF :OLD.TRANGTHAI <> 'CHƯA THANH TOÁN' THEN
            RAISE_APPLICATION_ERROR(-20061, 'Chỉ được xác nhận thanh toán hoá đơn đang ở trạng thái: CHƯA THANH TOÁN');
        end if;
    end if;

    SELECT COUNT(1)
    INTO V_COUNT
    FROM CHI_TIET_HOA_DON_THUE_SAN
    WHERE MAHD = :OLD.MAHD
      AND IS_DELETED = 0
      AND TRANGTHAI = 'ĐÃ XÁC NHẬN';

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'Hoá đơn không có chi tiết thuê sân hợp lệ để thanh toán');
    end if;
end;

--RB62
CREATE OR REPLACE TRIGGER TRG_AU_DONE_HOA_DON_CTHD
    AFTER UPDATE OF TRANGTHAI
    ON HOA_DON
    FOR EACH ROW

BEGIN
    IF :OLD.TRANGTHAI <> 'ĐÃ THANH TOÁN' AND :NEW.TRANGTHAI = 'ĐÃ THANH TOÁN' THEN
        UPDATE CHI_TIET_HOA_DON_THUE_SAN
        SET TRANGTHAI = 'ĐÃ HOÀN THÀNH'
        WHERE MAHD = :NEW.MAHD
          AND TRANGTHAI = 'ĐANG SỬ DỤNG'
          AND IS_DELETED = 0;

        UPDATE CHI_TIET_HOA_DON_DICH_VU_DA_DUNG
        SET TRANGTHAI = 'ĐÃ HOÀN THÀNH'
        WHERE MAHD = :NEW.MAHD
          AND TRANGTHAI = 'ĐANG SỬ DỤNG'
          AND IS_DELETED = 0;
    end if;


end;
/

--RB60
CREATE OR REPLACE PROCEDURE PRC_DIEU_CHINH_TON_SAN_PHAM(
    P_MASP IN SAN_PHAM.MASP%TYPE,
    P_DELTA IN NUMBER
)
AS
    V_SL_TON SAN_PHAM.SL_TON%TYPE;
BEGIN
    SELECT SL_TON
    INTO V_SL_TON
    FROM SAN_PHAM
    WHERE MASP = P_MASP
      AND IS_DELETED = 0
        FOR UPDATE;

    IF V_SL_TON + P_DELTA < 0 THEN
        RAISE_APPLICATION_ERROR(
                -20090,
                'So luong ton san pham khong du.'
        );
    END IF;

    UPDATE SAN_PHAM
    SET SL_TON = SL_TON + P_DELTA
    WHERE MASP = P_MASP
      AND IS_DELETED = 0;
END;
/

CREATE OR REPLACE PROCEDURE PRC_DIEU_CHINH_TON_DUNG_CU(
    P_MADC IN DUNG_CU_THE_THAO.MADC%TYPE,
    P_DELTA IN NUMBER
)
AS
    V_SL_TON DUNG_CU_THE_THAO.SL_TON%TYPE;
BEGIN
    SELECT SL_TON
    INTO V_SL_TON
    FROM DUNG_CU_THE_THAO
    WHERE MADC = P_MADC
      AND IS_DELETED = 0
        FOR UPDATE;

    IF V_SL_TON + P_DELTA < 0 THEN
        RAISE_APPLICATION_ERROR(
                -20091,
                'So luong ton dung cu khong du.'
        );
    END IF;

    UPDATE DUNG_CU_THE_THAO
    SET SL_TON = SL_TON + P_DELTA
    WHERE MADC = P_MADC
      AND IS_DELETED = 0;
END;
/

CREATE OR REPLACE TRIGGER TRG_CTNH_CAP_NHAT_TON_SAN_PHAM
    AFTER INSERT OR UPDATE OR DELETE
    ON CHI_TIET_NHAP_HANG
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:NEW.MASP, :NEW.SLTHUCNHAP);
        END IF;

    ELSIF DELETING THEN
        IF :OLD.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:OLD.MASP, -:OLD.SLTHUCNHAP);
        END IF;

    ELSIF UPDATING THEN
        IF :OLD.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:OLD.MASP, -:OLD.SLTHUCNHAP);
        END IF;

        IF :NEW.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:NEW.MASP, :NEW.SLTHUCNHAP);
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CTNDC_CAP_NHAT_TON_DUNG_CU
    AFTER INSERT OR UPDATE OR DELETE
    ON CHI_TIET_NHAP_DUNG_CU
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:NEW.MADC, :NEW.SLTHUCNHAP);
        END IF;

    ELSIF DELETING THEN
        IF :OLD.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:OLD.MADC, -:OLD.SLTHUCNHAP);
        END IF;

    ELSIF UPDATING THEN
        IF :OLD.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:OLD.MADC, -:OLD.SLTHUCNHAP);
        END IF;

        IF :NEW.IS_DELETED = 0 THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:NEW.MADC, :NEW.SLTHUCNHAP);
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CTHD_DV_CAP_NHAT_TON_SAN_PHAM
    BEFORE INSERT OR UPDATE OR DELETE
    ON CHI_TIET_HOA_DON_DICH_VU_DA_DUNG
    FOR EACH ROW
BEGIN
    IF DELETING OR UPDATING THEN
        IF :OLD.MASP IS NOT NULL
            AND :OLD.IS_DELETED = 0
            AND :OLD.TRANGTHAI IN ('ĐANG SỬ DỤNG', 'ĐÃ HOÀN THÀNH') THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:OLD.MASP, :OLD.SL);
        END IF;
    END IF;

    IF INSERTING OR UPDATING THEN
        IF :NEW.MASP IS NOT NULL
            AND :NEW.IS_DELETED = 0
            AND :NEW.TRANGTHAI IN ('ĐANG SỬ DỤNG', 'ĐÃ HOÀN THÀNH') THEN
            PRC_DIEU_CHINH_TON_SAN_PHAM(:NEW.MASP, -:NEW.SL);
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CTHD_DV_CAP_NHAT_TON_DUNG_CU
    BEFORE INSERT OR UPDATE OR DELETE
    ON CHI_TIET_HOA_DON_DICH_VU_DA_DUNG
    FOR EACH ROW
BEGIN
    IF DELETING OR UPDATING THEN
        IF :OLD.MADC IS NOT NULL
            AND :OLD.IS_DELETED = 0
            AND :OLD.TRANGTHAI = 'ĐANG SỬ DỤNG' THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:OLD.MADC, :OLD.SL);
        END IF;
    END IF;

    IF INSERTING OR UPDATING THEN
        IF :NEW.MADC IS NOT NULL
            AND :NEW.IS_DELETED = 0
            AND :NEW.TRANGTHAI = 'ĐANG SỬ DỤNG' THEN
            PRC_DIEU_CHINH_TON_DUNG_CU(:NEW.MADC, -:NEW.SL);
        END IF;
    END IF;
END;
/